spring:
  data:
    redis:
      # Redis 集群
      cluster:
        nodes: # 集群节点列表（ip:port）
          - 192.168.31.111:30003
          - 192.168.31.112:30003
          - 192.168.31.113:30003
        max-redirects: 3 # 最大重定向次数
      # Redis 密码（无密码则注释）
      password: Osborn@123
      # 选择数据库索引（0-15，默认0）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 10000
      # Lettuce 客户端配置（默认）
      lettuce:
        pool:
          # 最大活跃连接数（负数表示无限制）
          max-active: 8
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 0
          # 获取连接的最大等待时间（负数表示无限制）
          max-wait: 500ms